// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConversationCreate(arg1, arg2) {
  return window['go']['app']['App']['ConversationCreate'](arg1, arg2);
}

export function ConversationDelete(arg1) {
  return window['go']['app']['App']['ConversationDelete'](arg1);
}

export function ConversationGetByProjectPath(arg1) {
  return window['go']['app']['App']['ConversationGetByProjectPath'](arg1);
}

export function ConversationInfo(arg1) {
  return window['go']['app']['App']['ConversationInfo'](arg1);
}

export function ConversationList() {
  return window['go']['app']['App']['ConversationList']();
}

export function ConversationSend(arg1, arg2) {
  return window['go']['app']['App']['ConversationSend'](arg1, arg2);
}

export function ConversationSendWithCallback(arg1, arg2, arg3) {
  return window['go']['app']['App']['ConversationSendWithCallback'](arg1, arg2, arg3);
}

export function ConversationSendWithEvents(arg1, arg2) {
  return window['go']['app']['App']['ConversationSendWithEvents'](arg1, arg2);
}

export function ConversationUpdate(arg1) {
  return window['go']['app']['App']['ConversationUpdate'](arg1);
}

export function DialogOpenDirectory() {
  return window['go']['app']['App']['DialogOpenDirectory']();
}

export function EnvClearCache() {
  return window['go']['app']['App']['EnvClearCache']();
}

export function EnvDetectAll() {
  return window['go']['app']['App']['EnvDetectAll']();
}

export function EnvDetectByName(arg1) {
  return window['go']['app']['App']['EnvDetectByName'](arg1);
}

export function EnvGetDetectorNames() {
  return window['go']['app']['App']['EnvGetDetectorNames']();
}

export function EnvGetStatus() {
  return window['go']['app']['App']['EnvGetStatus']();
}

export function SystemOpenFile(arg1) {
  return window['go']['app']['App']['SystemOpenFile'](arg1);
}

export function SystemOpenTerminal(arg1) {
  return window['go']['app']['App']['SystemOpenTerminal'](arg1);
}

export function SystemRevealInFinder(arg1) {
  return window['go']['app']['App']['SystemRevealInFinder'](arg1);
}

export function WorkspaceClose() {
  return window['go']['app']['App']['WorkspaceClose']();
}

export function WorkspaceCopyFile(arg1, arg2) {
  return window['go']['app']['App']['WorkspaceCopyFile'](arg1, arg2);
}

export function WorkspaceCreateDirectory(arg1) {
  return window['go']['app']['App']['WorkspaceCreateDirectory'](arg1);
}

export function WorkspaceCreateFile(arg1, arg2) {
  return window['go']['app']['App']['WorkspaceCreateFile'](arg1, arg2);
}

export function WorkspaceDeleteFile(arg1) {
  return window['go']['app']['App']['WorkspaceDeleteFile'](arg1);
}

export function WorkspaceGetCurrent() {
  return window['go']['app']['App']['WorkspaceGetCurrent']();
}

export function WorkspaceGetFullPath(arg1) {
  return window['go']['app']['App']['WorkspaceGetFullPath'](arg1);
}

export function WorkspaceGetInfo() {
  return window['go']['app']['App']['WorkspaceGetInfo']();
}

export function WorkspaceIsOpen() {
  return window['go']['app']['App']['WorkspaceIsOpen']();
}

export function WorkspaceList() {
  return window['go']['app']['App']['WorkspaceList']();
}

export function WorkspaceListFiles() {
  return window['go']['app']['App']['WorkspaceListFiles']();
}

export function WorkspaceMoveFile(arg1, arg2) {
  return window['go']['app']['App']['WorkspaceMoveFile'](arg1, arg2);
}

export function WorkspaceOpen(arg1) {
  return window['go']['app']['App']['WorkspaceOpen'](arg1);
}

export function WorkspaceReadFile(arg1) {
  return window['go']['app']['App']['WorkspaceReadFile'](arg1);
}

export function WorkspaceRemove(arg1) {
  return window['go']['app']['App']['WorkspaceRemove'](arg1);
}

export function WorkspaceRenameFile(arg1, arg2) {
  return window['go']['app']['App']['WorkspaceRenameFile'](arg1, arg2);
}

export function WorkspaceSelect(arg1) {
  return window['go']['app']['App']['WorkspaceSelect'](arg1);
}

export function WorkspaceWriteFile(arg1, arg2) {
  return window['go']['app']['App']['WorkspaceWriteFile'](arg1, arg2);
}
