// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {conversation} from '../models';
import {models} from '../models';

export function BeforeClose(arg1:context.Context):Promise<boolean>;

export function ConversationCreate(arg1:string,arg2:string):Promise<conversation.Conversation>;

export function ConversationDelete(arg1:string):Promise<void>;

export function ConversationGetByProjectPath(arg1:string):Promise<conversation.Conversation>;

export function ConversationInfo(arg1:string):Promise<conversation.Conversation>;

export function ConversationList():Promise<Array<conversation.Conversation>>;

export function ConversationSend(arg1:string,arg2:string):Promise<conversation.Conversation>;

export function ConversationSendWithCallback(arg1:string,arg2:string,arg3:any):Promise<conversation.Conversation>;

export function ConversationSendWithEvents(arg1:string,arg2:string):Promise<void>;

export function ConversationUpdate(arg1:conversation.Conversation):Promise<void>;

export function DialogOpenDirectory():Promise<string>;

export function EnvClearCache():Promise<void>;

export function EnvDetectAll():Promise<models.EnvironmentInfo>;

export function EnvDetectByName(arg1:string):Promise<models.DetectionResult>;

export function EnvGetDetectorNames():Promise<Array<string>>;

export function EnvGetStatus():Promise<models.EnvironmentInfo>;

export function LogFrontend(arg1:string):Promise<void>;

export function SystemOpenClaudeTerminal():Promise<void>;

export function SystemOpenFile(arg1:string):Promise<void>;

export function SystemOpenTerminal(arg1:string):Promise<void>;

export function SystemRevealInFinder(arg1:string):Promise<void>;

export function WorkspaceClose():Promise<void>;

export function WorkspaceCopyFile(arg1:string,arg2:string):Promise<void>;

export function WorkspaceCreateDirectory(arg1:string):Promise<void>;

export function WorkspaceCreateFile(arg1:string,arg2:string):Promise<void>;

export function WorkspaceDeleteFile(arg1:string):Promise<void>;

export function WorkspaceGetActiveConversation():Promise<string>;

export function WorkspaceGetCurrent():Promise<string>;

export function WorkspaceGetFullPath(arg1:string):Promise<string>;

export function WorkspaceGetInfo():Promise<models.WorkspaceInfo>;

export function WorkspaceIsOpen():Promise<boolean>;

export function WorkspaceList():Promise<Array<models.WorkspaceInfo>>;

export function WorkspaceListFiles():Promise<Array<models.FileInfo>>;

export function WorkspaceMoveFile(arg1:string,arg2:string):Promise<void>;

export function WorkspaceOpen(arg1:string):Promise<models.WorkspaceInfo>;

export function WorkspaceReadFile(arg1:string):Promise<string>;

export function WorkspaceRemove(arg1:string):Promise<void>;

export function WorkspaceRenameFile(arg1:string,arg2:string):Promise<void>;

export function WorkspaceSelect(arg1:string):Promise<void>;

export function WorkspaceSetActiveConversation(arg1:string):Promise<void>;

export function WorkspaceWriteFile(arg1:string,arg2:string):Promise<void>;
